spring:
  application:
    name: everyteen  # 어플리케이션 이름 설정

  jpa:
    hibernate:
      ddl-auto: update  # 테이블이 없을 경우 생성, 테이블이 있을 경우 변경사항을 반영
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
