services:
  backend:
    image: 'jhungminwoo/everyteen-be-app:latest'
    container_name: everyteen-be-app
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
      TZ: Asia/Seoul  # 타임존 설정
    depends_on:
      - postgres
    networks:
      - everyteen-network
    restart: on-failure
    
  nginx_ui:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_manager
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '81:81' # Public HTTPS Port
      - '443:443' # Admin Web Port
    volumes:
      - /home/ubuntu/nginx_proxy_manager/data:/data
      - /home/ubuntu/letsencrypt:/etc/letsencrypt
    networks:
      - everyteen-network

  postgres:
      image: postgres:16-alpine
      container_name: postgres
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - /home/ubuntu/db/data:/var/lib/postgresql/data
        - /home/ubuntu/db/initdb.d:/docker-entrypoint-initdb.d
      ports:
        - 5432:5432  # PostgreSQL 기본 포트
      networks:
        - everyteen-network
  
networks:
  everyteen-network:
    driver: bridge
    external: true